version: '3.4'

services:
  triton_server:
    container_name: dietv-tis-22.04
    image: $IMAGE
    privileged: true
    ports:
      - $HTTP_P
      - $GRPC_P
      - $PROM_P
    deploy:
     resources:
       reservations:
         devices:
           - driver: nvidia
             capabilities: [gpu]
    volumes:
      - ${MODEL_REPOSITORY}:/models
    command: ["tritonserver", "--model-repository=/models"] 
